### ISSUE TITLE
Assalomu alaykum Azamat aka. Bu yerda linkka margin bergandan ko'ra header ga padding bersek yaxshiroq bo'sa kerak

### ISSUE THREAD

**Issue by mashhurbek2005** [Azamatjon0110/bookmark-azamatjon#1]
![image](https://user-images.githubusercontent.com/105698306/176832024-fe2af96d-a544-4dd3-b9d3-5a5ed7904f8a.png)

**Comment by Azamatjon0110** [comment]
Axa rahmat men eski maketdagi display fixeddagi code bn adashtirib yuboribman
