### ISSUE TITLE
Bu yerda <a> ga padding ni sal ko'proq bersek yaxshi bo'lardi. Chunki maketda a ning tepa va pastida default joyi bor.

### ISSUE THREAD

**Issue by mashhurbek2005** [Azamatjon0110/bookmark-azamatjon#2]
![image](https://user-images.githubusercontent.com/105698306/176833389-a5dbf534-6d1a-4443-ae69-fa01a5a9bbfe.png)

**Comment by Azamatjon0110** [comment]
haa men textni default joyi borligiga etibor bermabman to'g'riladim 😊
