### ISSUE TITLE
Bu yerda <ul> ning padding-left i qolib ketgan. To'grilab qo'ysek zo'r bo'lardi

### ISSUE THREAD

**Issue by mashhurbek2005** [Azamatjon0110/bookmark-azamatjon#3]
![image](https://user-images.githubusercontent.com/105698306/176833756-db297fbb-0521-494c-96b6-e0d078d37683.png)

**Comment by Azamatjon0110** [comment]
haa tushunarli halaqit bermagani uchun olmagandim rahmat
